# Generated by Django 4.1.3 on 2022-11-09 15:25

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("attrs", django_mysql.models.DynamicField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
