# Generated by Django 4.1.3 on 2022-11-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brandname",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
